Add deno to PATH

diff --git a/runtime/bootstrap b/runtime/bootstrap
--- a/runtime/bootstrap
+++ b/runtime/bootstrap
@@ -60,11 +60,11 @@ function error {
 
 # If the script fails we try and determine why.
 function investigate {
-  [ -f $SCRIPT_DIR/amz-deno ] \
-   || error "missing amz-deno executable"
+  [ -f $SCRIPT_DIR/bin/deno ] \
+   || error "missing deno executable"
 
-  $SCRIPT_DIR/amz-deno eval 'Deno.version.deno' \
-   || error "bad amz-deno executable"
+  deno eval 'Deno.version.deno' \
+   || error "bad deno executable"
 
   [ -f $LAMBDA_TASK_ROOT/$HANDLER_FILE ] \
    || error "missing expected handler file '$HANDLER_FILE'"
@@ -73,15 +73,15 @@ function investigate {
     [ -f $DENO_LOCK ] \
      || error "missing lock file '$DENO_LOCK'"
     # This second check might be unecessary (in that it would be caught by the 'unable to compile')
-    DENO_DIR=/tmp/deno_dir NO_COLOR=true $SCRIPT_DIR/amz-deno fetch $DENO_FETCH_FLAGS $LAMBDA_TASK_ROOT/$HANDLER_FILE &> /tmp/lock.out \
+    DENO_DIR=/tmp/deno_dir NO_COLOR=true deno fetch $DENO_FETCH_FLAGS $LAMBDA_TASK_ROOT/$HANDLER_FILE &> /tmp/lock.out \
      || error "lock file error: $(cat /tmp/lock.out)"
   fi
 
-  DENO_DIR=/tmp/deno_dir NO_COLOR=true $SCRIPT_DIR/amz-deno fetch $DENO_FETCH_FLAGS $LAMBDA_TASK_ROOT/$HANDLER_FILE 2> /dev/null \
+  DENO_DIR=/tmp/deno_dir NO_COLOR=true deno fetch $DENO_FETCH_FLAGS $LAMBDA_TASK_ROOT/$HANDLER_FILE 2> /dev/null \
    || error "unable to compile $HANDLER_FILE"
 
   echo "import { $HANDLER_NAME } from '$LAMBDA_TASK_ROOT/$HANDLER_FILE';" > /tmp/runtime-test.js
-  DENO_DIR=/tmp/deno_dir NO_COLOR=true $SCRIPT_DIR/amz-deno fetch $DENO_IMPORTMAP /tmp/runtime-test.js 2> /dev/null \
+  DENO_DIR=/tmp/deno_dir NO_COLOR=true deno fetch $DENO_IMPORTMAP /tmp/runtime-test.js 2> /dev/null \
    || error "$HANDLER_FILE must export a function named '$HANDLER_NAME'";
 
   # FIXME perhaps a bug in bootstrap? Should we always exit 1? Or not?
@@ -203,11 +203,11 @@ cp -R $LAMBDA_TASK_ROOT/$DENO_DIR/gen/. /tmp/deno_dir/gen &> /dev/null \
  || echo "warn: unable to import '$DENO_DIR/' as DENO_DIR"
 
 # FIXME remove DENO_FLAGS=DENO_FLAGS environment variable setting (used in testing only).
-DENO_DIR=/tmp/deno_dir DENO_FLAGS=$DENO_FLAGS NO_COLOR=true $SCRIPT_DIR/amz-deno run $DENO_FLAGS /tmp/runtime.js \
+DENO_DIR=/tmp/deno_dir DENO_FLAGS=$DENO_FLAGS NO_COLOR=true deno run $DENO_FLAGS /tmp/runtime.js \
  || investigate;
 
 # For debugging purposes of the bootstrap script itself it's useful to change the extension to /tmp/runtime.ts
 # and run this code instead to get more verbose and type errors during testing.
 # Note: on production you will see the verbose error message anyway in cloudwatch logs.
-# DENO_DIR=/tmp/deno_dir DENO_FLAGS=$DENO_FLAGS NO_COLOR=true $SCRIPT_DIR/amz-deno run $DENO_FLAGS /tmp/runtime.ts &> /tmp/fail.out \
+# DENO_DIR=/tmp/deno_dir DENO_FLAGS=$DENO_FLAGS NO_COLOR=true deno run $DENO_FLAGS /tmp/runtime.ts &> /tmp/fail.out \
 #  || error "error: $(cat /tmp/fail.out)"
